### ISSUE TITLE
[@SoftDelete]db.delete() uncorrectly cannot syncing data to Elasticsearch when use "@softDelete" 

### ISSUE THREAD

**Issue by duishancunzhang** [ebean-orm/avaje-ebeanorm-elastic#12]
<strong>The question is :
when invoke SoftDelete,[mysql] execute "update" operation after that [ElasticSearch]  followed it,do a "update bulk".
But i am glad to see [ElasticSearch] can receive a "delete bulk" request.
</strong>

**Comment by rbygrave** [comment]
Hi,

Can you improve the description of what you see and what you expect to see.

You can do this by including the logs of what happens including the SQL statements and the calls to the ElasticSearch Bulk API.  

Thanks

**Comment by duishancunzhang** [comment]
i appreciate for your reply.And here is my code and logs
```
[Code]
```
userPoint.logicalDelete();

```

[logs]
```
10:13:33.931 [qtp1095352419-30] DEBUG org.avaje.ebean.SQL - txn[s459093033] update user_point set modifier=?, modify_time=?, deleted=? where id=?; --bind(40508fbd24d0432fa9aa879f76728464,2016-07-18 10:13:33.93,true,1895f42945d242dd816862b3e01d4ea9,)
10:13:33.933 [qtp1095352419-30] DEBUG org.avaje.ebean.SUM - txn[s459093033] SoftDelete [UserPoint] [1895f42945d242dd816862b3e01d4ea9]
<strong>i think here should console "delete bulk",not "update bulk" or nothing</strong>
```

thank you

**Comment by rbygrave** [comment]
> i think here should console "delete bulk",not "update bulk" or nothing

I believe you are expecting a "soft delete" to result in a delete from the ElasticSearch index.

The current behavior is that a "soft delete" results in a SQL update ... and that in turn results in a ElasticSearch index update (via the Bulk API).

This update of the index is the expected behaviour and deemed to be the correct behaviour.

Note that the index contains the "deleted" property and this value is now set to true (just as it is in the DB) and that this gives us the ability to search for the UserPoint with or without that predicate (deleted = true).

That is, we can search for the index taking into account soft delete ... find where ... deleted=true

Why do you want a "soft delete" to result in a delete from the ElasticSearch index?  What issue does this cause you?

**Comment by duishancunzhang** [comment]
thanks,i admire your opinion 
<stong>" search for the index taking into account soft delete ... find where ... deleted=true"</strong> it can be a good solution.
😊 in addition, i am expecting a delete from the ElasticSearch index in a "soft delete" function.

**Comment by duishancunzhang** [comment]
Hi
another question is that a "update bulk api" cannot work in a "soft delete" invoke.
here is my versions of ebean reference:
```
<!-- ebean -->
        <ebean.version>7.15.1</ebean.version>
        <ebean-elastic.version> 1.3.1</ebean-elastic.version>
```
in debug mode i have seen ebean return  "DocStoreMode.IGNORE"  in case of persistType="SOFT_DELETE" so that userPoint entity cannot in turns update the ElasticSearch index "deleted=true" etc

**Comment by duishancunzhang** [comment]
Hi
i work out a solution for this issue.How about adding an case "SOFT_DELETE" to do hard delete against ElasticSearch
[DocStoreBeanBaseAdapter]
```
private DocStoreMode getMode(PersistRequest.Type persistType) {
    switch (persistType) {
      case INSERT:
        return insert;
      case UPDATE:
        return update;
      case SOFT_DELETE:
        return update;
      case DELETE:
        return delete;
      default:
        return DocStoreMode.IGNORE;
    }
  }
```
[Logs]
```
17:04:32.318 [qtp1046665075-26] DEBUG org.avaje.ebean.SUM - txn[s116823513] SoftDelete [PointDetail] [4fcff5ce713b447585ac11c74684e7ac]
17:04:32.318 [qtp1046665075-26] DEBUG org.avaje.ebean.SUM - txn[s116823513] SoftDelete [PointDetail] [670c33ddcd6441a0a889d28f7c71a002]
17:04:32.318 [qtp1046665075-26] DEBUG org.avaje.ebean.SUM - txn[s116823513] SoftDelete [PointDetail] [9f2892c440a242158358707c9cd05401]
17:04:32.319 [qtp1046665075-26] DEBUG org.avaje.ebean.SUM - txn[s116823513] SoftDelete [PointDetail] [be36ed9ea8d345d7ab979eb2b3af4ec9]
17:04:32.319 [qtp1046665075-26] DEBUG org.avaje.ebean.SUM - txn[s116823513] SoftDelete [PointDetail] [d5a8a09082994bb4ba36814d238a51fb]
17:04:32.319 [qtp1046665075-26] DEBUG org.avaje.ebean.TXN - txn[s116823513] Commit
17:04:32.320 [ebean-main3] TRACE org.avaje.ebeanservice.elastic.BULK - ElasticBulkMessage Request:
{"delete":{"_id":"89f4a99a21b24460a1c6b6552678ddc4","_type":"userpoint","_index":"userpoint"}}
 {"delete":{"_id":"4fcff5ce713b447585ac11c74684e7ac","_type":"pointdetail","_index":"pointdetail"}}
 {"delete":{"_id":"670c33ddcd6441a0a889d28f7c71a002","_type":"pointdetail","_index":"pointdetail"}}
 {"delete":{"_id":"9f2892c440a242158358707c9cd05401","_type":"pointdetail","_index":"pointdetail"}}
 {"delete":{"_id":"be36ed9ea8d345d7ab979eb2b3af4ec9","_type":"pointdetail","_index":"pointdetail"}}
 {"delete":{"_id":"d5a8a09082994bb4ba36814d238a51fb","_type":"pointdetail","_index":"pointdetail"}}
```

**Comment by rbygrave** [comment]
I presume you want some way to configure the behavior such that it either does the update against the index (as it does currently) or does a delete against the index (as you would like it for your scenario).

Can you explain why you want this behavior?

Thanks

**Comment by rbygrave** [comment]
I believe you are not making a change request here so I'll close this for now. Reopen if needed. 
Thanks, Rob.
