### ISSUE TITLE
Q: Can I use NodeBuilder.local(true).http(false) es node provider? (as embedded server for testing)

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm-elastic#2]
For test or embedded es server, i can not open other port.
Now,  i just found `docstore.url` conifg.

**Comment by rbygrave** [comment]
No you can't.

It is currently not supported to use an embedded ElasticSearch server without http.

**Comment by icode** [comment]
@rbygrave support it? or interface local services, support i custom base impl

**Comment by rbygrave** [comment]
Logged as #3
